#!/usr/bin/env python3
"""Build the site's generated JS from source data. Run from the site/ directory.

  python3 scripts/build-data.py                regenerate manifests/variants/,
                                               manifests-data.js, models.js
  python3 scripts/build-data.py --sync-models  also read upstream's model catalog
                                               (src/shared/modelCatalog.json) and
                                               merge its ids into models.json first
                                               (additive merge)

manifests/<slug>.hire.json is the SOURCE OF TRUTH for each role; per-provider
variants are derived (model/commandFlags carry over only on the role's native
provider). models.json is the source of truth for model SUGGESTIONS (a manifest
may use any model string; suggestions never validate).
"""
import json, os, re, sys, tempfile, urllib.request

# Windows consoles default to a legacy code page (cp1252), which cannot print the
# arrows and dashes in this script's output and used to crash it on the last line.
for stream in (sys.stdout, sys.stderr):
    try:
        stream.reconfigure(encoding='utf-8', errors='replace')
    except (AttributeError, ValueError):
        pass


def read_json(path):
    # Explicit UTF-8: the platform default on Windows is cp1252, which misreads
    # every non-ASCII character in the manifests and writes it back corrupted.
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def write_text(path, text):
    """Write UTF-8 atomically, keeping the file's existing line endings.

    The tree mixes LF and CRLF files; rewriting one with the other turns a
    one-line change into a whole-file diff. A new file gets LF. The temp file +
    os.replace means an interrupted run never leaves a half-written file."""
    newline = '\n'
    try:
        with open(path, 'rb') as f:
            if b'\r\n' in f.read():
                newline = '\r\n'
    except FileNotFoundError:
        pass
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path) or '.', prefix='.build-data-', suffix='.tmp')
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline=newline) as out:
            out.write(text)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise


def json_text(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + '\n'


PROVIDERS = ['claude', 'antigravity', 'codex', 'cursor']
# The app's pickers read src/shared/modelCatalog.json (the hardcoded arrays in
# config.ts this script used to scrape are gone), so sync from the catalog.
UPSTREAM_CATALOG = ('https://raw.githubusercontent.com/chaitanyagiri/munder-difflin/'
                    'main/src/shared/modelCatalog.json')

# ── optional: sync models.json from upstream's model catalog ────────────────
if '--sync-models' in sys.argv:
    catalog = json.loads(urllib.request.urlopen(UPSTREAM_CATALOG, timeout=15).read().decode())
    def block(prov):
        return [m['id'] for m in catalog.get('providers', {}).get(prov, []) if m.get('id')]
    models = read_json('models.json')
    for prov in ['claude', 'antigravity']:
        ups = block(prov)
        local_only = [m for m in models.get(prov, []) if m not in ups]
        models[prov] = ups + local_only
        print(f'{prov}: {len(ups)} upstream + {len(local_only)} local-only')
    import datetime
    models['updated'] = datetime.date.today().isoformat()
    write_text('models.json', json_text(models))
    print('models.json synced from upstream modelCatalog.json')

# ── manifests → variants + manifests-data.js ────────────────────────────────
os.makedirs('manifests/variants', exist_ok=True)
idx = read_json('manifests/index.json')
data = []
for f in idx:
    base = read_json(f'manifests/{f}')
    base_provider = base.get('provider', 'claude')
    if base_provider == 'agy':
        base_provider = 'antigravity'
    slug = f.replace('.hire.json', '')
    variants = {}
    for p in PROVIDERS:
        v = dict(base)
        v['provider'] = p
        if p != base_provider:
            v.pop('model', None)
            v.pop('commandFlags', None)
        vfile = f'variants/{slug}.{p}.hire.json'
        write_text(f'manifests/{vfile}', json_text(v))
        variants[p] = {'file': vfile, 'manifest': v}
    data.append({'file': f, 'manifest': base, 'baseProvider': base_provider, 'variants': variants})

write_text('manifests-data.js',
           '/* AUTO-GENERATED by scripts/build-data.py — do not edit by hand.\n'
           '   Also serves as the file:// fallback (fetch is blocked there). */\n'
           'window.HIRES_DATA = ' + json.dumps(data, indent=2, ensure_ascii=False) + ';\n')

# ── models.json → models.js ─────────────────────────────────────────────────
models = read_json('models.json')
models.pop('_comment', None)
write_text('models.js',
           '/* AUTO-GENERATED from models.json by scripts/build-data.py — do not edit.\n'
           '   Update models.json (or run build-data.py --sync-models), then rebuild. */\n'
           'window.HIRE_MODELS = ' + json.dumps(models, indent=2, ensure_ascii=False) + ';\n')

print(f'{len(data)} roles × {len(PROVIDERS)} providers → manifests/variants/, manifests-data.js, models.js')
